# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  urlshortener:
    build:
      context: "C:\\Users\\User\\source\\repos\\Url-Shortener\\UrlShortener"
      dockerfile: "UrlShortener/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/UrlShortener.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\User\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\User\\.nuget\\packages"
    image: "urlshortener:dev"
    ports: []
    volumes:
    - "C:\\Users\\User\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Users\\User\\source\\repos\\Url-Shortener\\UrlShortener\\UrlShortener:/app:rw"
    - "C:\\Users\\User\\source\\repos\\Url-Shortener\\UrlShortener:/src:rw"
    working_dir: "/app"
